language: python
python:
- '3.7'
install: pip install -r requirements/testing.txt
script: tox
notifications:
  email: false
  slack:
    secure: bspblSgG9+zjTl4+jBYedw88RZV9TESLPpWjz+5U/6IrsPVIlDa1lUvwiD7SzXBFAaUeq8LwYEmTLbIoluuyllvA3fTeqYXoJKYReKx9p/34STJY29qknoUlL7nC7gcyX0FnJ41fFtee7hDiqFAc2J0z86JZBD+Zjj3pUPBZ5IU=
  on_success: change
  on_failure: always
